#!/bin/bash
set -e

# 🏰 PocketCoder Setup Script
# This script initializes the environment, generates secure secrets, and sets up initial users.

echo "🏰 Starting PocketCoder Setup..."

# 1. GENERATE SECRETS
echo "🔑 Generating secure credentials..."
AGENT_PASSWORD=$(openssl rand -base64 24)
ADMIN_PASSWORD=$(openssl rand -base64 24)
SUPERUSER_PASSWORD=$(openssl rand -base64 24)

# 2. LOAD EXISTING SECRETS (If any)
GEMINI_API_KEY=""
if [ -f .env ]; then
    echo "⚠️  .env already exists. Backing up to .env.bak"
    cp .env .env.bak
    GEMINI_API_KEY=$(grep "^GEMINI_API_KEY=" .env | cut -d'=' -f2- || echo "")
elif [ -f .env.bak ]; then
    GEMINI_API_KEY=$(grep "^GEMINI_API_KEY=" .env.bak | cut -d'=' -f2- || echo "")
fi

# 3. WRITE TO ENV
cat > .env <<EOF
COMPOSE_PROJECT_NAME=pocketcoder
# Container Ports
PORT=3000
POCKETBASE_URL=http://pocketbase:8090
BRAIN_URL=http://opencode:3000

# ------------------------------------------------------------------
# 🛡️ SECURE CREDENTIALS (Generated by setup script)
# ------------------------------------------------------------------

# 🌌 POCKETBASE DASHBOARD (Super Administrator)
POCKETBASE_SUPERUSER_EMAIL=user@pocketcoder.app
POCKETBASE_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}

# 👤 APP IDENTITY (The Human / Authorizer)
POCKETBASE_USER_EMAIL=admin@pocketcoder.local
POCKETBASE_USER_PASSWORD=${ADMIN_PASSWORD}

# 🤖 AGENT IDENTITY (The Bot)
AGENT_EMAIL=agent@pocketcoder.local
AGENT_PASSWORD=${AGENT_PASSWORD}

# 🧠 AI REASONING
GEMINI_API_KEY=${GEMINI_API_KEY}
EOF

echo "✅ Secrets cached in .env (Add this file to .gitignore!)"

# 4. START POCKETBASE (To let it seed/migrate)
echo "🚀 Booting up the Core (PocketBase)..."
docker-compose up -d pocketbase

# 5. WAIT FOR HEALTHCHECK
echo "⏳ Waiting for PocketBase to be ready..."
until curl -s -f http://localhost:8090/api/health > /dev/null; do
    sleep 2
    echo -n "."
done
echo " Ready!"

# 6. RESTART TO ENSURE EVERYTHING IS LOADED
echo "🔄 Finalizing configuration..."
docker-compose restart pocketbase

echo "
🎉 PocketCoder Setup Complete.

🤖 Agent Identity:
   Email: agent@pocketcoder.local
   Pass:  ${AGENT_PASSWORD}

👤 Admin User:
   Email: admin@pocketcoder.local
   Pass:  ${ADMIN_PASSWORD}

🔑 Superuser Password (Dashboard):
   Email: user@pocketcoder.app
   Pass:  ${SUPERUSER_PASSWORD}

🛑 SAVE THESE CREDENTIALS NOW. They are stored in .env but you should keep them safe.
"
