#!/bin/bash
set -e

# 🏰 PocketCoder Setup Script
# This script initializes the environment, generates secure secrets, and sets up initial users.

echo "🏰 Starting PocketCoder Setup..."

# 1. GENERATE SECRETS
echo "🔑 Generating secure credentials..."
AGENT_PASSWORD=$(openssl rand -base64 24)
ADMIN_PASSWORD=$(openssl rand -base64 24)

# 2. WRITE TO ENV
if [ -f .env ]; then
    echo "⚠️  .env already exists. Backing up to .env.bak"
    cp .env .env.bak
fi

# Ensure we keep existing vars but update passwords
cat > .env <<EOF
COMPOSE_PROJECT_NAME=pocketcoder
# Container Ports
PORT=3000
POCKETBASE_URL=http://pocketbase:8090
BRAIN_URL=http://opencode:3000

# ------------------------------------------------------------------
# 🛡️ SECURE CREDENTIALS (Generated by setup script)
# ------------------------------------------------------------------
AGENT_EMAIL=agent@pocketcoder.local
AGENT_PASSWORD=${AGENT_PASSWORD}

ADMIN_EMAIL=admin@pocketcoder.local
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

echo "✅ Secrets cached in .env (Add this file to .gitignore!)"

# 3. START POCKETBASE (Background)
echo "🚀 Booting up the Core (PocketBase)..."
docker-compose up -d pocketbase

# 4. WAIT FOR HEALTHCHECK
echo "⏳ Waiting for PocketBase to be ready..."
until curl -s -f http://localhost:8090/api/health > /dev/null; do
    sleep 2
    echo -n "."
done
echo " Ready!"

# 5. APPLY CONFIGURATION
echo "🔄 Applying configuration to the Core..."
docker-compose restart pocketbase

echo "
🎉 PocketCoder Setup Complete.

🤖 Agent Identity:
   Email: agent@pocketcoder.local
   Pass:  ${AGENT_PASSWORD}

👤 Admin User:
   Email: admin@pocketcoder.local
   Pass:  ${ADMIN_PASSWORD}

🛑 SAVE THESE CREDENTIALS NOW. They are stored in .env but you should keep them safe.
"
