import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:flutter/foundation.dart';
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart';
import 'package:cubit_ui_flow/cubit_ui_flow.dart' as cubit_ui_flow;
import 'bootstrap.config.dart';
import 'package:pocketcoder_flutter/infrastructure/core/connectivity_override.dart';
import 'package:pocketcoder_flutter/domain/notifications/push_service.dart';
import 'package:pocketcoder_flutter/domain/billing/billing_service.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Global service locator instance

final GetIt getIt = GetIt.instance;

/// Configures all dependency injection bindings.
/// Generated by build_runner from @injectable and @module annotations.
@InjectableInit()
Future<void> configureDependencies() async {
  await getIt.init();
}

/// Bootstraps the entire application.
///
/// Call this once from main() before runApp().
Future<void> bootstrap() async {
  debugPrint('Bootstrap: Starting...');

  // 0. Load environment variables
  try {
    await dotenv.load(fileName: ".env");
    debugPrint('Bootstrap: .env loaded');
  } catch (e) {
    debugPrint('Bootstrap: Warning - No .env file found: $e');
  }

  // Fix for Chrome Incognito offline detection bug in connectivity_plus
  if (kIsWeb) {
    debugPrint('Bootstrap: Setting connectivity override for Web');
    ConnectivityPlatform.instance = WebConnectivityOverride();
  }

  try {
    debugPrint('Bootstrap: Configuring dependencies...');
    await configureDependencies();
    debugPrint('Bootstrap: Dependencies configured');

    // Initialize the push service
    final pushService = getIt<PushService>();
    await pushService.initialize();

    // Initialize the billing service
    final billingService = getIt<BillingService>();
    await billingService.initialize();

    // 2. Register UI flow service (depends on localization/feedback/loading)
    debugPrint('Bootstrap: Registering UI flow service...');
    _registerUiFlowService();
    debugPrint('Bootstrap: UI flow service registered');

    // 3. Configure ErrorPrivserver for privacy-preserving error reporting
    debugPrint('Bootstrap: Configuring ErrorPrivserver...');
    _configureErrorPrivserver();
    debugPrint('Bootstrap: ErrorPrivserver configured');

    debugPrint('Bootstrap: Complete');
  } catch (e, stack) {
    debugPrint('Bootstrap: FAILED - $e');
    debugPrint('Bootstrap: Stack trace:\n$stack');
    rethrow;
  }
}

void _registerUiFlowService() {
  if (!getIt.isRegistered<cubit_ui_flow.IUiFlowService>()) {
    getIt.registerLazySingleton<cubit_ui_flow.IUiFlowService>(
      () => cubit_ui_flow.UiFlowService(
        localization: getIt<cubit_ui_flow.ILocalizationService>(),
        feedback: getIt<cubit_ui_flow.IFeedbackService>(),
        loading: getIt<cubit_ui_flow.ILoadingService>(),
      ),
    );
  }
}

/// Configure ErrorPrivserver for privacy-preserving error reporting.
void _configureErrorPrivserver() {
  // Note: Actual configuration requires repository implementations.
  // This is a placeholder for where you would wire up your error reporting.
  // See quanitya example for full implementation with ErrorBoxRepository.
  debugPrint('ErrorPrivserver: Initialization placeholder');
}
