import 'package:get_it/get_it.dart';
import 'package:pocketbase/pocketbase.dart';
import 'package:injectable/injectable.dart';
import 'package:flutter/foundation.dart';
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart';
import 'package:cubit_ui_flow/cubit_ui_flow.dart' as cubit_ui_flow;

import 'bootstrap.config.dart';
import 'app_dependency_module.dart';

import 'package:pocketcoder_flutter/infrastructure/core/connectivity_override.dart';
import 'package:pocketcoder_flutter/domain/notifications/push_service.dart';
import 'package:pocketcoder_flutter/domain/billing/billing_service.dart';
import 'package:pocketcoder_flutter/domain/auth/auth_session_coordinator.dart';
import 'package:pocketcoder_flutter/domain/auth/i_auth_repository.dart';
import 'package:pocketcoder_flutter/application/boot/boot_routing_decider.dart';
import 'package:pocketcoder_flutter/app_router.dart';
import 'package:pocketcoder_flutter/domain/deployment/i_server_readiness_check.dart';
import 'package:pocketcoder_flutter/domain/deployment/i_instance_existence_resolver.dart';
import 'package:pocketcoder_flutter/domain/deployment/i_deployment_auth_status.dart';
import 'package:pocketcoder_flutter/infrastructure/deployment/self_host_server_readiness_check.dart';
import 'package:pocketcoder_flutter/infrastructure/core/pocketcoder_api_client.dart';
import 'package:pocketcoder_flutter/infrastructure/core/auth_aware_http_client.dart';
import 'package:pocketcoder_flutter/infrastructure/core/caddy_ca_pinning_http_client.dart';
import 'package:pocketcoder_flutter/infrastructure/deployment/ca_pin_recovery.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_error_privserver/flutter_error_privserver.dart';
import 'package:pocketcoder_flutter/infrastructure/errors/error_code_mapper.dart';
import 'package:pocketcoder_flutter/infrastructure/errors/diagnostic_capture.dart';
import 'package:pocketcoder_flutter/infrastructure/auth/auth_session_effects.dart';
import 'package:pocketcoder_flutter/infrastructure/auth/deployment_cache_effects.dart';
import 'package:pocketcoder_flutter/infrastructure/core/base_dao.dart';
import 'package:cubit_ui_flow/cubit_ui_flow.dart' show IExceptionKeyMapper;

/// Global service locator instance

final GetIt getIt = GetIt.instance;

/// Configures all dependency injection bindings.
/// Generated by build_runner from @injectable and @module annotations.
@InjectableInit()
Future<void> configureDependencies({
  AppDependencyModule? appModule,
}) async {
  // App-specific bindings must exist before the generated shared graph is
  // built because shared services depend on them by interface. The nullable
  // compatibility path lets older app targets migrate independently; new
  // app entry points should always provide a module.
  appModule?.register(getIt);
  await getIt.init();
}

/// Bootstraps the entire application.
///
/// Call this once from main() before runApp().
Future<void> bootstrap({AppDependencyModule? appModule}) async {
  installPocketCoderGlobalErrorHandlers();
  debugPrint('Bootstrap: Starting...');

  // Fix for Chrome Incognito offline detection bug in connectivity_plus
  if (kIsWeb) {
    debugPrint('Bootstrap: Setting connectivity override for Web');
    ConnectivityPlatform.instance = WebConnectivityOverride();
  }

  try {
    debugPrint('Bootstrap: Configuring dependencies...');
    await configureDependencies(appModule: appModule);
    if (!getIt.isRegistered<AuthSessionCoordinator>()) {
      getIt.registerLazySingleton<AuthSessionCoordinator>(
        () => AuthSessionCoordinator(getIt<IAuthRepository>()),
      );
    }
    if (!getIt.isRegistered<IServerReadinessCheck>()) {
      getIt.registerLazySingleton<IServerReadinessCheck>(
        () => SelfHostServerReadinessCheck(
          authRepository: getIt<IAuthRepository>(),
        ),
      );
    }
    if (!getIt.isRegistered<BootRoutingDecider>()) {
      getIt.registerLazySingleton<BootRoutingDecider>(
        () => BootRoutingDecider(
          readinessCheck: getIt<IServerReadinessCheck>(),
          authCoordinator: getIt<AuthSessionCoordinator>(),
          harnessAuthRepository: getIt(),
          router: AppRouter.router,
          instanceExistenceResolver:
              getIt.isRegistered<IInstanceExistenceResolver>()
                  ? getIt<IInstanceExistenceResolver>()
                  : null,
          deploymentAuthStatus: getIt.isRegistered<IDeploymentAuthStatus>()
              ? getIt<IDeploymentAuthStatus>()
              : null,
        ),
      );
    }
    getIt<PocketCoderApiClient>().setAuthSessionCoordinator(
      getIt<AuthSessionCoordinator>(),
    );
    if (getIt.isRegistered<CaPinRecovery>()) {
      final caPinRecovery = getIt<CaPinRecovery>();
      getIt<CaddyCaPinningHttpClient>().attachRecovery(caPinRecovery);
      getIt<PocketCoderApiClient>().attachCaPinRecovery(caPinRecovery);
      debugPrint('Bootstrap: CaPinRecovery wired to both HTTP transports');
      await caPinRecovery.warmUp();
      debugPrint('Bootstrap: CA pin warm-up complete');
    } else {
      debugPrint(
          'Bootstrap: CaPinRecovery not registered -- skipping (expected on FOSS)');
    }
    BaseDao.configureSessionCoordinator(getIt<AuthSessionCoordinator>());
    if (!getIt.isRegistered<DeploymentCacheEffects>()) {
      getIt.registerLazySingleton<DeploymentCacheEffects>(
        () => DeploymentCacheEffects(
          getIt<AuthSessionCoordinator>(),
          getIt<PocketBase>(),
        ),
      );
    }
    getIt<DeploymentCacheEffects>().start();
    final httpClient = getIt<http.Client>();
    if (httpClient is AuthAwareHttpClient) {
      httpClient.state.refresh = getIt<AuthSessionCoordinator>().refresh;
    }
    debugPrint('Bootstrap: Dependencies configured');

    final pushService = getIt<PushService>();
    await pushService.initialize();

    final billingService = getIt<BillingService>();
    await billingService.initialize();

    // Start after push and billing initialization. The coordinator replay
    // handles an already-persisted session without blocking bootstrap.
    if (!getIt.isRegistered<AuthSessionEffects>()) {
      getIt.registerLazySingleton<AuthSessionEffects>(
        () => AuthSessionEffects(
          getIt<AuthSessionCoordinator>(),
          billingService,
          pushService,
        ),
      );
    }
    getIt<AuthSessionEffects>().start();

    debugPrint('Bootstrap: Registering UI flow service...');
    _registerUiFlowService();
    debugPrint('Bootstrap: UI flow service registered');

    debugPrint('Bootstrap: Configuring ErrorPrivserver...');
    _configureErrorPrivserver();
    await pocketCoderDiagnosticCapture.flush();
    debugPrint('Bootstrap: ErrorPrivserver configured');

    debugPrint('Bootstrap: Complete');
  } catch (e, stack) {
    debugPrint('Bootstrap: FAILED - $e');
    debugPrint('Bootstrap: Stack trace:\n$stack');
    await pocketCoderDiagnosticCapture.capture(
      error: e,
      stackTrace: stack,
      source: 'Bootstrap',
      operation: 'startup',
    );
    rethrow;
  }
}

void _registerUiFlowService() {
  if (!getIt.isRegistered<cubit_ui_flow.IUiFlowService>()) {
    getIt.registerLazySingleton<cubit_ui_flow.IUiFlowService>(
      () => cubit_ui_flow.UiFlowService(
        localization: getIt<cubit_ui_flow.ILocalizationService>(),
        feedback: getIt<cubit_ui_flow.IFeedbackService>(),
        loading: getIt<cubit_ui_flow.ILoadingService>(),
      ),
    );
  }
}

/// Configure ErrorPrivserver for privacy-preserving error reporting.
void _configureErrorPrivserver() {
  ErrorPrivserver.configure(
    ErrorPrivserverConfig(
      storage: getIt<ErrorBoxStorage>(),
      reporter: (_) async =>
          false, // no-op: no network transmission, see spec §3
      errorCodeMapper: PocketCoderErrorCodeMapper.mapError,
      exceptionMapper: (error) => getIt<IExceptionKeyMapper>().map(error),
    ),
  );
}
