#!/bin/bash
set -e

# Post-install: generate .env from Elestio-provided environment variables
cat > .env <<EOF
POCKETBASE_SUPERUSER_EMAIL=${POCKETBASE_SUPERUSER_EMAIL}
POCKETBASE_SUPERUSER_PASSWORD=${POCKETBASE_SUPERUSER_PASSWORD}
POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
AGENT_EMAIL=${AGENT_EMAIL}
AGENT_PASSWORD=${AGENT_PASSWORD}
OPEN_NOTEBOOK_ENCRYPTION_KEY=${OPEN_NOTEBOOK_ENCRYPTION_KEY}
PN_PROVIDER=${PN_PROVIDER}
PN_URL=${PN_URL}
PN_RELAY_SECRET=${PN_RELAY_SECRET}
EOF

docker compose up -d
