// Server-authoritative mirror of AG-UI events for the active chat. The
// Goose-backed c1 service is the source of truth for history; this table is
// purely a client-side cache so the Flutter UI can rehydrate after process
// death and replay frames at the cursor. Rows are keyed by (chatId, seq) so
// warm-resume upserts replace stale frames and the watcher always emits in
// monotonic order.
//
// Backed by real drift codegen (`@DriftDatabase`) — see `agent_cache_db.g.dart`
// (generated by drift_dev; run `dart run build_runner build` after editing
// this file). The reactive `watchChat` stream is drift's own query-invalidating
// `.watch()`, not a hand-rolled notifier.
import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:injectable/injectable.dart';

part 'agent_cache_db.g.dart';

/// One cached AG-UI frame for a chat, keyed by the server-allocated seq.
class CachedEvent {
  const CachedEvent({
    required this.chatId,
    required this.seq,
    required this.type,
    required this.json,
  });

  final String chatId;
  final int seq;
  final String type;
  final String json;
}

@DataClassName('ChatEventRow')
class ChatEvents extends Table {
  TextColumn get chatId => text()();
  IntColumn get seq => integer()();
  TextColumn get type => text()();
  TextColumn get json => text()();

  @override
  Set<Column> get primaryKey => {chatId, seq};
}

/// Drift-backed cache for chat events. Production resolves a single on-disk
/// instance via the default constructor; tests construct one directly with a
/// memory `NativeDatabase.memory()` executor through [AgentCacheDb.forExecutor].
@lazySingleton
@DriftDatabase(tables: [ChatEvents])
class AgentCacheDb extends _$AgentCacheDb {
  /// Production constructor — opens an on-disk SQLite database at
  /// `$getApplicationDocumentsDirectory()/agent_cache.sqlite` via drift_flutter.
  AgentCacheDb() : super(driftDatabase(name: 'agent_cache'));

  /// Test/embedded constructor — accepts any [QueryExecutor] (typically
  /// `NativeDatabase.memory()` so each test owns a fresh empty database).
  AgentCacheDb.forExecutor(super.executor);

  @override
  int get schemaVersion => 1;

  /// Insert or replace a single event. Conflict resolution is keyed on the
  /// composite primary key (chatId, seq), so replays of the same seq from the
  /// server overwrite the prior payload rather than duplicating it.
  Future<void> upsertEvent(
    String chatId,
    int seq,
    String type,
    String json,
  ) async {
    await into(chatEvents).insertOnConflictUpdate(
      ChatEventsCompanion.insert(
        chatId: chatId,
        seq: seq,
        type: type,
        json: json,
      ),
    );
  }

  /// Reactive watcher for a single chat, ordered by server-allocated seq.
  /// Emits the current snapshot synchronously on subscription and again on
  /// every subsequent mutation (upsertEvent/clearChat) for this chatId.
  Stream<List<CachedEvent>> watchChat(String chatId) {
    final query = select(chatEvents)
      ..where((t) => t.chatId.equals(chatId))
      ..orderBy([(t) => OrderingTerm.asc(t.seq)]);
    return query.watch().map(
          (rows) => rows
              .map(
                (r) => CachedEvent(
                  chatId: r.chatId,
                  seq: r.seq,
                  type: r.type,
                  json: r.json,
                ),
              )
              .toList(growable: false),
        );
  }

  /// Highest seq observed for the chat, or null when no rows are cached yet.
  /// Callers use this as the SSE resume cursor (`?cursor=<n>`).
  Future<int?> maxSeq(String chatId) async {
    final query = selectOnly(chatEvents)
      ..addColumns([chatEvents.seq.max()])
      ..where(chatEvents.chatId.equals(chatId));
    final row = await query.getSingleOrNull();
    return row?.read(chatEvents.seq.max());
  }

  /// Drop all cached frames for a single chat. Other chats are untouched so
  /// concurrent conversations keep their replayable history.
  Future<void> clearChat(String chatId) async {
    await (delete(chatEvents)..where((t) => t.chatId.equals(chatId))).go();
  }
}
