// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-W4mlA__OSbSYT4f1nI5Xvin6r21ink',
    appId: '1:703071534401:web:c56e2f77c672f906d735c0',
    messagingSenderId: '703071534401',
    projectId: 'pocketcoder-bc547',
    authDomain: 'pocketcoder-bc547.firebaseapp.com',
    storageBucket: 'pocketcoder-bc547.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHalqP-Fd7m7MDwaHV-8Vq3Nkr8n46D5s',
    appId: '1:703071534401:android:04eda9b69d42a73bd735c0',
    messagingSenderId: '703071534401',
    projectId: 'pocketcoder-bc547',
    storageBucket: 'pocketcoder-bc547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJNdH_5oLKbpI4FiU09SoKO1pOyVme3Ro',
    appId: '1:703071534401:ios:23050bcaed4031d9d735c0',
    messagingSenderId: '703071534401',
    projectId: 'pocketcoder-bc547',
    storageBucket: 'pocketcoder-bc547.firebasestorage.app',
    iosBundleId: 'org.pocketcoder.app',
  );
}
