import 'package:injectable/injectable.dart';
import '../../domain/sop/i_sop_repository.dart';
import '../../domain/sop/sop.dart';
import '../../domain/proposal/proposal.dart';
import '../../domain/exceptions.dart';
import '../../core/try_operation.dart';
import 'sop_daos.dart';

@LazySingleton(as: ISopRepository)
class SopRepository implements ISopRepository {
  final SopDao _sopDao;
  final ProposalDao _proposalDao;

  SopRepository(this._sopDao, this._proposalDao);

  @override
  Stream<List<Sop>> watchSops() {
    return _sopDao.watch(sort: '-updated');
  }

  @override
  Stream<List<Proposal>> watchProposals() {
    return _proposalDao.watch(sort: '-updated');
  }

  @override
  Future<void> approveProposal(String id) async {
    return tryMethod(
      () async {
        await _proposalDao.save(id, {
          'status': 'approved',
        });
      },
      SopException.new,
      'approveProposal',
    );
  }

  @override
  Future<void> createProposal(Proposal proposal) async {
    return tryMethod(
      () async {
        final data = proposal.toJson();
        data.remove('id'); // ID is generated by PocketBase
        await _proposalDao.save(null, data);
      },
      SopException.new,
      'createProposal',
    );
  }
}
