/// Generated by generate_models.py — do not edit by hand.
class Collections {
  static const String users = 'users';
  static const String chats = 'chats';
  static const String sandboxAgents = 'sandbox_agents';
  static const String toolPermissions = 'permission_mode_tools';
  static const String healthchecks = 'healthchecks';
  static const String mcpServers = 'mcp_servers';
  static const String devices = 'devices';
  static const String notificationRules = 'notification_rules';
  static const String harnesses = 'harnesses';
  static const String models = 'models';
  static const String harnessModels = 'harness_models';
  static const String providerKeys = 'provider_keys';
  static const String prompts = 'prompts';
  static const String pocoConfigs = 'agent_profiles';
  static const String agentSessions = 'agent_sessions';
  static const String scheduleOwners = 'schedule_owners';
  static const String harnessInstances = 'harness_instances';
  static const String harnessAccounts = 'harness_accounts';
  static const String harnessAccountSelections = 'harness_account_selections';
  static const String harnessAuthAttempts = 'harness_auth_attempts';
  static const String permissionModes = 'permission_modes';
  static const String skills = 'skills';
  static const String gitSshCredentials = 'git_ssh_credentials';
  static const String gitRepositoryAccess = 'git_repository_access';

  static const List<String> all = [
    users,
    chats,
    sandboxAgents,
    toolPermissions,
    healthchecks,
    mcpServers,
    devices,
    notificationRules,
    harnesses,
    models,
    harnessModels,
    providerKeys,
    prompts,
    pocoConfigs,
    agentSessions,
    scheduleOwners,
    harnessInstances,
    harnessAccounts,
    harnessAccountSelections,
    harnessAuthAttempts,
    permissionModes,
    skills,
    gitSshCredentials,
    gitRepositoryAccess,
  ];
}
