/// Generated by generate_models.py — do not edit by hand.
class Collections {
  static const String users = 'users';
  static const String aiPrompts = 'ai_prompts';
  static const String aiModels = 'ai_models';
  static const String aiAgents = 'ai_agents';
  static const String chats = 'chats';
  static const String messages = 'messages';
  static const String permissions = 'permissions';
  static const String sandboxAgents = 'sandbox_agents';
  static const String sshKeys = 'ssh_keys';
  static const String toolPermissions = 'tool_permissions';
  static const String healthchecks = 'healthchecks';
  static const String mcpServers = 'mcp_servers';
  static const String proposals = 'proposals';
  static const String sops = 'sops';
  static const String questions = 'questions';
  static const String devices = 'devices';
  static const String llmKeys = 'llm_keys';
  static const String modelSelection = 'model_selection';
  static const String llmProviders = 'llm_providers';
  static const String notificationRules = 'notification_rules';
  static const String cronJobs = 'cron_jobs';

  static const List<String> all = [
    users,
    aiPrompts,
    aiModels,
    aiAgents,
    chats,
    messages,
    permissions,
    sandboxAgents,
    sshKeys,
    toolPermissions,
    healthchecks,
    mcpServers,
    proposals,
    sops,
    questions,
    devices,
    llmKeys,
    modelSelection,
    llmProviders,
    notificationRules,
    cronJobs,
  ];
}
