/// Generated by generate_models.py — do not edit by hand.
class Collections {
  static const String users = 'users';
  static const String chats = 'chats';
  static const String sandboxAgents = 'sandbox_agents';
  static const String sshKeys = 'ssh_keys';
  static const String toolPermissions = 'tool_permissions';
  static const String healthchecks = 'healthchecks';
  static const String mcpServers = 'mcp_servers';
  static const String devices = 'devices';
  static const String notificationRules = 'notification_rules';
  static const String harnesses = 'harnesses';
  static const String models = 'models';
  static const String harnessModels = 'harness_models';
  static const String providerKeys = 'provider_keys';
  static const String prompts = 'prompts';
  static const String pocoConfigs = 'poco_configs';
  static const String agentSessions = 'agent_sessions';
  static const String scheduleOwners = 'schedule_owners';
  static const String harnessInstances = 'harness_instances';

  static const List<String> all = [
    users,
    chats,
    sandboxAgents,
    sshKeys,
    toolPermissions,
    healthchecks,
    mcpServers,
    devices,
    notificationRules,
    harnesses,
    models,
    harnessModels,
    providerKeys,
    prompts,
    pocoConfigs,
    agentSessions,
    scheduleOwners,
    harnessInstances,
  ];
}
