#!/bin/bash
set -e

echo "🔄 [Sovereign Docs] Starting polyglot documentation extraction..."

# Only remove files this script itself regenerates below -- privacy.md
# and reference/*.md other than backend.md are hand-maintained or
# generated by a different pipeline entirely.
rm -f ./src/content/docs/reference/backend.md
rm -rf ./src/content/docs/guides
find ./src/content/docs -maxdepth 1 \( -name '*.md' -o -name '*.mdx' \) ! -name 'privacy.md' -delete
mkdir -p ./src/content/docs/reference
mkdir -p ./src/content/docs/guides

# Programmatically generate Codebase Audit
echo "🦅 Generating Sovereign Audit..."
if [ -f "/app/scripts/generate_audit.sh" ]; then
  (cd /app && bash scripts/generate_audit.sh) || echo "⚠️ Audit generation had issues"
else
  echo "⚠️ generate_audit.sh not found, skipping audit generation"
fi

# Function to extract body content (skip H1 if present)
extract_body() {
  local file=$1
  if [ -f "$file" ]; then
    # Skip the first line (Title) to let Starlight handle it via frontmatter
    tail -n +2 "$file"
  else
    echo "⚠️ File not found: $file"
  fi
}

# 1. Sync Root Markdown Files
echo "📝 Syncing root guides..."

# The Docker dev container mounts the repo at /app; CI has no container,
# so the repo root there is one level up from website/, not two.
if [ -d "/app" ]; then
  ROOT_DIR="/app"
else
  ROOT_DIR=".."
fi

if [ -f "$ROOT_DIR/SECURITY.md" ]; then
  echo -e "---\ntitle: Security Architecture\ndescription: How PocketCoder enforces sovereign isolation.\nhead: []\n---\n" > ./src/content/docs/architecture.md
  extract_body "$ROOT_DIR/SECURITY.md" >> ./src/content/docs/architecture.md
else
  echo "⚠️ SECURITY.md not found at $ROOT_DIR"
fi

# 1b. Sync Guides
echo "📖 Syncing guides..."
for guide in ./guides/*.md; do
  if [ -f "$guide" ]; then
    name=$(basename "$guide" .md)
    title=$(echo "$name" | sed 's/_/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')
    echo -e "---\ntitle: $title\nhead: []\n---\n" > "./src/content/docs/guides/$name.md"
    extract_body "$guide" >> "./src/content/docs/guides/$name.md"
  fi
done

# 2. Extract Go Docs (c1 backend)
echo "🐹 Extracting Go docs..."
echo -e "---\ntitle: Backend Reference\nhead: []\n---\n" > ./src/content/docs/reference/backend.md
if command -v gomarkdoc &> /dev/null; then
  # gomarkdoc works best when run from the module root for all packages
  # We use --include-unexported if we want maximum context for the "Sovereign Audit"
  if [ -d "$ROOT_DIR/server/pocketbase" ]; then
    (cd "$ROOT_DIR/server/pocketbase" && gomarkdoc --include-unexported . ./internal/... ./pkg/...) >> ./src/content/docs/reference/backend.md || echo "⚠️ Go doc extraction had warnings"
  else
    echo "⚠️ server/pocketbase not found"
  fi
else
  echo "❌ Error: gomarkdoc not found"
fi

# The Rust sandbox proxy is dormant (moved to dormant/); its reference page is
# no longer generated. See dormant/README.md.

# 5. Extract Stats and Update Landing Page
# Extract TOTAL_CORE from the generated CODEBASE.md
if [ -f "$ROOT_DIR/CODEBASE.md" ]; then
  # Extract from the language table: | **Core total** | **41,143** | ... |
  TOTAL_CORE=$(grep '\*\*Core total\*\*' "$ROOT_DIR/CODEBASE.md" | awk -F'|' '{print $3}' | tr -d ' *')
else
  TOTAL_CORE="~41,000"
fi
echo "📊 Total Core Lines of Code: $TOTAL_CORE"

echo "📝 Updating index.mdx with real stats..."
cat > ./src/content/docs/index.mdx <<EOF
---
title: Welcome to PocketCoder
description: A personal research lab for Sovereign AI.
head: []
template: splash
hero:
  tagline: A Minimalist Sovereign AI Assistant Lab.
  actions:
    - text: Read the docs
      link: /architecture
      icon: right-arrow
      variant: primary
    - text: View on Codeberg
      link: https://codeberg.org/qtpi-bonding-org/pocketcoder
      icon: external
---
EOF

echo "✅ [Sovereign Docs] Extraction complete."
