#!/bin/sh
set -eu

# OpenCode accepts the same inline configuration generated by Ollama's
# integration command. Generate that small fragment at peer start so the
# model list follows the shared Ollama volume without a host-specific config
# file. Other ACP agents retain the audited adapter-only path unchanged.
#
# Was `"${1:-}" = "opencode"` -- main.go parses --cmd/--port as named flags
# (flag.String), so $1 here is always literally "--cmd", never the harness
# name; that check could never match. POCKETCODER_HARNESS_CLI_ID (seeded
# per harness, 1756000100_seed.go) is a real, reliable signal.
if [ "${POCKETCODER_HARNESS_CLI_ID:-}" = "opencode" ] && [ -z "${OPENCODE_CONFIG_CONTENT:-}" ]; then
  if config=$(node /usr/local/lib/pocketcoder/opencode-ollama-config.mjs); then
    export OPENCODE_CONFIG_CONTENT="$config"
  else
    echo "PocketCoder: starting OpenCode without local Ollama discovery" >&2
  fi
fi

exec /usr/local/bin/harness-adapter "$@"
