#!/bin/sh
set -eu

# OpenCode accepts the same inline configuration generated by Ollama's
# integration command. Generate that small fragment at peer start so the
# model list follows the shared Ollama volume without a host-specific config
# file. Other ACP agents retain the audited adapter-only path unchanged.
if [ "${1:-}" = "opencode" ] && [ -z "${OPENCODE_CONFIG_CONTENT:-}" ]; then
  if config=$(node /usr/local/lib/pocketcoder/opencode-ollama-config.mjs); then
    export OPENCODE_CONFIG_CONTENT="$config"
  else
    echo "PocketCoder: starting OpenCode without local Ollama discovery" >&2
  fi
fi

exec /usr/local/bin/harness-adapter "$@"
